# Generated by Django 5.0 on 2023-12-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Greeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "when",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
            ],
        ),

        migrations.CreateModel(
            name="Pushup",
            fields=[
                (
                    "user",
                    models.IntegerField(primary_key=True)
                ),
                (
                    "balance",
                    models.IntegerField(default=0)
                ),
                (
                    "datetime_updated",
                    models.DateTimeField(
                        verbose_name="datetime updated", auto_now=True
                    ),
                ),
            ],
        ),
    ]
